### ISSUE TITLE
All enumeration of queries throws ArangoServerException( ErrorNumber : 17, HttpStatusCode : 400 ) 

### ISSUE THREAD

**Issue by JulianMay** [ra0o0f/arangoclient.net#15]
It seems theres a problem with cursors (guessing).
For for reproduction:

```csharp
        [Test]
        public void CanQueryDB()
        {
            using (var db = new ArangoDatabase("http://localhost:8529", database: "test"))
            {
                var exDb = db.ListDatabases();
                if (exDb.Contains("test"))
                {
                    db.DropDatabase("test");
                }
                db.CreateDatabase("test");


                var obj = new SomeClass() {Key = "1", Text = "Heyheyhey!"};
                db.Insert<SomeClass>(obj);
                Assert.That(() =>

                    //How else would you do it?
                    db.Query<SomeClass>().Where(x => true).ToArray()

                    , Throws.Nothing);
            }
        }

        public class SomeClass
        {
            [DocumentProperty(Identifier = IdentifierType.Key)]
            public string Key;
            public string Text;
        }
```

When runnin Arango 2.7.0 or 2.6.9 (that's the versions I've tried), the following is thrown:

```
Message:	
ArangoDB.Client.ArangoServerException : expecting non-zero value for <batchSize>. ErrorNumber: 17 HttpStatusCode: 400

Stacktrace:
at ArangoDB.Client.BaseResultAnalyzer.ThrowIfNeeded(BaseResult baseResult)
   at ArangoDB.Client.Cursor.CursorAsyncEnumerator`1.<SetCurrent>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ArangoDB.Client.Cursor.CursorAsyncEnumerator`1.<MoveNextAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at ArangoDB.Client.Utility.TaskUtils.ResultSynchronizer[T](Task`1 task)
   at ArangoDB.Client.Cursor.CursorEnumerator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Xpectra.ReadServiceTests.Contexts.NotesReadModel.NotesEventHandlerTest.<CanQueryDB>b__6_0() in C:\Code\Xpectra\Tests\Xpectra.ReadServiceTests\Contexts\NotesReadModel\NotesEventHandlerTest.cs:line 74
   at NUnit.Framework.Constraints.GenericInvocationDescriptor`1.Invoke()
   at NUnit.Framework.Constraints.ExceptionInterceptor.Intercept(Object invocation)

```

I've also asked for help StackOverflow ( http://stackoverflow.com/questions/33102920/how-can-i-avoid-error-17-when-querying-with-arangodb-net-client ) - but maybe it belongs here?

/Julian

**Comment by JulianMay** [comment]
oh.... I see the current implementation of "AqlQueryable<T>.Where()" is *throw new NotImplementedException();*....
Probably not a new problem then?

**Comment by ra0o0f** [comment]
@JulianMay it not about cursor or linq, the problem happens at serializing aql options, im looking at it right now

**Comment by ra0o0f** [comment]
i fixed it, im publishing new nuget packages for it now.

**Comment by JulianMay** [comment]
Awesome, thanks for the quick solution!

**Comment by ra0o0f** [comment]
@JulianMay please feel free to open an issue for any other problem occurs
