### ISSUE TITLE
Sanitize transaction-scripts?

### ISSUE THREAD

**Issue by JulianMay** [ra0o0f/arangoclient.net#27]
I've just figured out why i keep getting the following exception:

ArangoDB.Client.ArangoServerException : missing/invalid action definition for transaction - Uncaught SyntaxError: Unexpected token ILLEGAL - SyntaxError: Unexpected token ILLEGAL
  at Function (native)
  at post_api_transaction (c:\Code\Xpectra\Dependencies\ArangoDB-2.7.1-win64\share\arangodb\js\actions\api-transaction.js:268:16)
  at Function.actions.defineHttp.callback (c:\Code\Xpectra\Dependencies\ArangoDB-2.7.1-win64\share\arangodb\js\actions\api-transaction.js:288:11)
. ErrorNumber: 10 HttpStatusCode: 400

... The input is not sanitized - even linebreaks in the script causes this exception.

It works when regex.replace'ing **@"[^\u0000-\u007F]"** and **@"\r\n?|\n"** with string.Empty.

This is a warning for others searching for "Unexpected token ILLEGAL", and a suggestion to have the client-framework handle input sanitazion :)

/Julian

**Comment by ra0o0f** [comment]
thakns @JulianMay, tomorrow i will release a new package, i will add the Sanitization of transaction script too.

**Comment by ra0o0f** [comment]
@JulianMay i'm working on this right now and want to do following:

- remove illegal tokens that are not between '' or ""
- add a setting property so users can disable sanitization

and i cant reproduce this, can you write a failing test for this please? and also what are the illegal tokens, can you list them all

**Comment by JulianMay** [comment]
Hey - sorry for the delay

I have not been able to find invalid characters besides than "\r\n?|\n". Test attached

[TransactionSanitazionTest.cs.txt](https://github.com/ra0o0f/arangoclient.net/files/47030/TransactionSanitazionTest.cs.txt)
