### ISSUE TITLE
Nullable DateTimeOffset de-serialization throws an exception

### ISSUE THREAD

**Issue by aft-ape** [ra0o0f/arangoclient.net#79]
Here's the demo code:
```csharp
using ArangoDB.Client;
using Newtonsoft.Json;
using System;
using System.Net;

namespace ConsoleApp1
{
    public class TestClass
    {
        [DocumentProperty(Identifier = IdentifierType.Key)]
        public string Id { get; set; }
        public DateTimeOffset? NullableDateTimeOffset { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Works just fine with Newtonsoft.Json defaults:");
            var json = JsonConvert.SerializeObject(new TestClass
            {
                Id = "test",
                NullableDateTimeOffset = DateTimeOffset.Now
            });
            Console.WriteLine(json);
            var obj = JsonConvert.DeserializeObject<TestClass>(json);
            Console.WriteLine(obj.NullableDateTimeOffset);
            Console.WriteLine("----------");

            Console.WriteLine("Similar test with ArangoDB fails:");
            ArangoDatabase.ChangeSetting(s =>
            {
                s.Database = "TestDatabase";
                s.Url = "http://localhost:8529";

                // you can set other settings if you need
                s.Credential = new NetworkCredential("root", "123456");
                s.SystemDatabaseCredential = new NetworkCredential("root", "123456");
            });
            using (var db = ArangoDatabase.CreateWithSetting())
            {
                db.Collection("TestCollection").Insert(new TestClass
                {
                    Id = "TestDocument",
                    NullableDateTimeOffset = DateTimeOffset.Now
                });
                try
                {
                    var loadedObj = db.Collection("TestCollection").Document<TestClass>("TestDocument");
                    Console.WriteLine(loadedObj.NullableDateTimeOffset);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                }
            }

            Console.ReadKey();
        }
    }
}
```
And here's the output:
```
Works just fine with Newtonsoft.Json defaults:
{"Id":"test","NullableDateTimeOffset":"2017-05-30T10:03:29.0679454+08:00"}
5/30/2017 10:03:29 AM +08:00
----------
Similar test with ArangoDB fails:
Newtonsoft.Json.JsonSerializationException:
Error setting value to 'NullableDateTimeOffset' on 'ConsoleApp1.TestClass'. --->
System.InvalidCastException:
Unable to cast object of type 'System.DateTime' to type 'System.Nullable`1[System.DateTimeOffset]'.
```
I would assume that the code above should work. ArangoDB seems to handle `DateTimeOffset` correctly if it is not `Nullable`.

**Comment by ra0o0f** [comment]
@aft-ape thanks for reporting this, it's fixed and new nuget packages will be available soon

**Comment by AntonyVorontsov** [comment]
I guess i hav to re-open this. I have got the same problem but with async methods.
Here is the demo code similar to original author's code.

```cs
using ArangoDB.Client;
using System;
using System.Net;
using System.Threading.Tasks;

namespace ArangoTest
{
    class Item
    {
        public string Name { get; set; }
        public DateTimeOffset CreatedAt { get; set; }
        public DateTimeOffset? UpdatedAt { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            ExecuteArangoTest().GetAwaiter().GetResult();
            Console.ReadKey();
        }

        private static async Task ExecuteArangoTest()
        {
            ArangoDatabase.ChangeSetting(s =>
            {
                s.Database = "for_testing_purposes";
                s.Url = "http://localhost:8529";
                s.Credential = new NetworkCredential("root", "root");
                s.SystemDatabaseCredential = new NetworkCredential("root", "root");
            });

            const string collectionName = "items";
            using (var db = ArangoDatabase.CreateWithSetting())
            {
                var item = new Item
                {
                    Name = "Name",
                    CreatedAt = DateTimeOffset.Now,
                    UpdatedAt = DateTimeOffset.Now
                };
                var result = await db.Collection(collectionName).InsertAsync(item);
                try
                {
                    // works
                    var exists = await db.Collection(collectionName).ExistsAsync(result.Id);

                    // does not work
                    var otherExistsMethod = await db.ExistsAsync<Item>(result.Id);
                    // does not work either
                    var loadedObject = await db.Collection(collectionName).DocumentAsync<Item>(result.Id);
                    Console.WriteLine(loadedObject.CreatedAt);
                    Console.WriteLine(loadedObject.UpdatedAt);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                }
            }
        }
    }
}
```

Output is the same

```
Newtonsoft.Json.JsonSerializationException: Error setting value to 'UpdatedAt' on 'ArangoTest.Item'. ---> System.InvalidCastException: Unable to cast object of type 'System.DateTime' to type 'System.Nullable`1[System.DateTimeOffset]'.
   at lambda_method(Closure , Object , Object )
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at ArangoDB.Client.Serialization.DocumentSerializer.DeserializeSingleResult[T](Stream stream, JObject& jObject)
   at ArangoDB.Client.Http.HttpCommand.<RequestDistinctResult>d__37`1.MoveNext()
```
and so on....
So the problem is still there, Nullable DateTimeOffset fails to deserialize.
P.S. I am using the driver of 0.7.60 version.

**Comment by AntonyVorontsov** [comment]
@ra0o0f Do not wanna open a new issue. Hope you can help me.
Thank you in advance
